---
# tasks file for ansible-motd
- name: Define MOTD
  template:
    src: motd.j2
    dest: /etc/motd
- name: Define issue
  template:
    src: motd.j2
    dest: /etc/issue
- name: Define issue.net
  template:
    src: motd.j2
    dest: /etc/issue.net

  tags:
    - motd
